export const SNIPPET_ICONS: Record<string, string> = {
  IntroCard: "film",
  LowerThird: "monitor",
  EndCard: "check",
  StatCallout: "bolt",
  QuoteCard: "chat",
  LogoBumper: "sparkle",
  CalloutBanner: "info",
  ListReveal: "list",
  CodeSnippet: "code",
  SymbolBug: "image",
  AccountCTA: "check",
  PathReveal: "sparkle",
  RisingStarsList: "list",
  LogoGridStrip: "image",
  FourQuadrant: "grid",
  BeforeAfter: "aspect",
  EventCard: "info",
  MCPLaunchFrame: "layers",
  ActorStoreCard: "image",
  ActorCard: "layers",
  EventContour: "sparkle",
  HiringCard: "list",
  ChartReveal: "bolt",
  PromptBox: "chat",
  AiChat: "chat",
};
